### ISSUE TITLE
Apple M1 native do not properly load when using an Azul JDK for ARM64

### ISSUE THREAD

**Issue by jzy3d** [jzy3d/vtk-java-natives#7]
# Problem

Fail to load native for the M1 plateform with exception stating 
```
mach-o, but wrong architecture
```

In this case, there is no platform selection, we directly try to load the M1 platform, so this should not relate to #10 .

## Full example

```
vtk-native version: 0.1
Java version: 11.0.13
Current platform: mac_aarch64
VtkNativeLibraries : Using natives provided by VtkNativeLibrariesImplMacOS_M1
VtkNativeLibraries : Start extracting natives to /var/folders/d2/85g_sxm91rg71yyky4gg6l6h0000gn/T/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/d2/85g_sxm91rg71yyky4gg6l6h0000gn/T/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib: dlopen(/private/var/folders/d2/85g_sxm91rg71yyky4gg6l6h0000gn/T/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib, 1): no suitable image found.  Did find:
	/private/var/folders/d2/85g_sxm91rg71yyky4gg6l6h0000gn/T/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib: mach-o, but wrong architecture
	/private/var/folders/d2/85g_sxm91rg71yyky4gg6l6h0000gn/T/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib: mach-o, but wrong architecture
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.Runtime.load(Runtime.java:756)
	at ch.unibas.cs.gravis.vtkjavanativelibs.VtkNativeLibraries.initialize(VtkNativeLibraries.java:132)
	at ch.unibas.cs.gravis.vtkjavanativelibs.VtkNativeLibraries.initialize(VtkNativeLibraries.java:158)
	at ch.unibas.cs.gravis.vtkjavanativelibs.Demo_VtkNativeLibrariesImplMacOS_M1.main(Demo_VtkNativeLibrariesImplMacOS_M1.java:27)
```

# Investigations
Everything is fine when using an OpenJDK for x86_64 (+Rosetta), but this is because x86 natives are loaded (Check that the jar was really built with M1 natives?)

Everything is fine when running `TestVtkNativeLibrariesImplMacOS_M1` which can properly
- unpack natives from M1 jar
- invoke vtkVersion class
- was run from Azul JDK

**Comment by jzy3d** [comment]
# Compare target architecture of the two files

The lib file used in the demo program indeed seams to be a x86 file!

```
lipo -info /private/var/folders/d2/85g_sxm91rg71yyky4gg6l6h0000gn/T/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib    (base) 
Non-fat file: /private/var/folders/d2/85g_sxm91rg71yyky4gg6l6h0000gn/T/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib is architecture: x86_64
```

Whereas the file used in the test program seams to be a arm64 file

```
lipo -info /Users/martin/Dev/jzy3d/public/vtk-java-natives/vtkJavaNativesMacOSM1Impl/target/natives/m1/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib
Non-fat file: /Users/martin/Dev/jzy3d/public/vtk-java-natives/vtkJavaNativesMacOSM1Impl/target/natives/m1/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib is architecture: arm64
```

# Compare hash of the two files

The file are actually different despite they should come from the same jar

```
shasum -a 256 /Users/martin/Dev/jzy3d/public/vtk-java-natives/vtkJavaNativesMacOSM1Impl/target/natives/m1/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib 
5bf287b5ab79362f42d2358a55125b34fef97a997b5e0651ee35f52bbc3d2eaa  /Users/martin/Dev/jzy3d/public/vtk-java-natives/vtkJavaNativesMacOSM1Impl/target/natives/m1/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib
```

```
shasum -a 256 /private/var/folders/d2/85g_sxm91rg71yyky4gg6l6h0000gn/T/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib   (base) 
c660a20268a29fc0707a632e771a6bc4b23fb1fd9a707c1cb2428029cc095f66  /private/var/folders/d2/85g_sxm91rg71yyky4gg6l6h0000gn/T/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib

```

# Compare target files and size of the two links

File content differ between test and demo program output

```
martin@osxm1 /A/Q/C/MacOS> ls -ahl /Users/martin/Dev/jzy3d/public/vtk-java-natives/vtkJavaNativesMacOSM1Impl/target/natives/m1/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib 
-rw-r--r--  1 martin  staff   418K  6 déc 10:36 /Users/martin/Dev/jzy3d/public/vtk-java-natives/vtkJavaNativesMacOSM1Impl/target/natives/m1/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib
martin@osxm1 /A/Q/C/MacOS> ls -ahl /private/var/folders/d2/85g_sxm91rg71yyky4gg6l6h0000gn/T/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib         (base) 
-rw-r--r--  1 martin  staff   395K  6 déc 10:38 /private/var/folders/d2/85g_sxm91rg71yyky4gg6l6h0000gn/T/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib
```

but also with the source lib folder

```
martin@osxm1 /A/Q/C/MacOS> ls -ahl /Users/martin/Dev/jzy3d/public/vtk-java-natives/vtkJavaNativesMacOSM1Impl/src/main/resources/ch/unibas/cs/gravis/vtkjavanativelibs/impl/libvtkWrappingTols-9.1.dylib 
lrwxr-xr-x  1 martin  staff    31B 16 sep 15:38 /Users/martin/Dev/jzy3d/public/vtk-java-natives/vtkJavaNativesMacOSM1Impl/src/main/resources/ch/unibas/cs/gravis/vtkjavanativelibs/impl/libvtkWrappingTools-9.1.dylib -> libvtkWrappingTools-9.1.1.dylib
martin@osxm1 /A/Q/C/MacOS> ls -ahl /Users/martin/Dev/jzy3d/public/vtk-java-natives/vtkJavaNativesMacOSM1Impl/src/main/resources/ch/unibas/cs/gravis/vtkjavanativelibs/impl/libvtkWrappingTools-9.1.1.dylib
lrwxr-xr-x  1 martin  staff    35B 16 sep 15:38 /Users/martin/Dev/jzy3d/public/vtk-java-natives/vtkJavaNativesMacOSM1Impl/src/main/resources/ch/unibas/cs/gravis/vtkjavanativelibs/impl/libvtkWrappingTools-9.1.1.dylib -> libvtkWrappingTools-9.1.9.1.0.dylib
martin@osxm1 /A/Q/C/MacOS> ls -ahl /Users/martin/Dev/jzy3d/public/vtk-java-natives/vtkJavaNativesMacOSM1Impl/src/main/resources/ch/unibas/cs/gravis/vtkjavanativelibs/impl/libvtkWrappingTools-9.1.9.1.0.dylib 
-rwxr-xr-x  1 martin  staff   418K 16 nov  2021 /Users/martin/Dev/jzy3d/public/vtk-java-natives/vtkJavaNativesMacOSM1Impl/src/main/resources/ch/unibas/cs/gravis/vtkjavanativelibs/impl/libvtkWrappingTools-9.1.9.1.0.dylib
```

What is visible is here is that the library file that have been extracted from the archive are only links !
Indeed, the VTK library file patterns are
- `libSomething-9.1.dylib` : link
- `libSomething-9.1.1.dylib` : link
- `libSomething-9.1.9.1.0.dylib` : actual library

This patterns is what we see in the src/main/resource file containing the compiled library. On the other hand the directory where the library are extracted ONLY contain files with pattern `libSomething-9.1.dylib`, where the file is not a link anymore BUT an actual library.

**There is a chance that the link are replaced by actual file either while building the archive, either while extracting the archive.**

# Monitoring extraction 

From test / IDE

`file:/Users/martin/Dev/jzy3d/public/vtk-java-natives/vtkJavaNativesMacOSM1Impl/target/classes/ch/unibas/cs/gravis/vtkjavanativelibs/impl/libvtkParallelCore-9.1.dylib /Users/martin/Dev/jzy3d/public/vtk-java-natives/vtkJavaNativesMacOSM1Impl/./target/natives/m1/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkParallelCore-9.1.dylib
`

shows that only links are copied to the execution environment but AS final file. It is still not clear at what time the file get transformed!

**Comment by jzy3d** [comment]
x86 link

```
martin@osxm1 ~/D/j/p/v/v/s/m/r/c/u/c/g/v/impl (main)> realpath libvtkWrappingTools-9.1.dylib                                                                                        (base) 
/Users/martin/Dev/jzy3d/public/vtk-java-natives/**vtkJavaNativesMacOSImpl**/src/main/resources/ch/unibas/cs/gravis/vtkjavanativelibs/impl/libvtkWrappingTools-9.1.9.1.0.dylib
```

arm link

```
martin@osxm1 ~/D/j/p/v/v/s/m/r/c/u/c/g/v/impl (main)> realpath libvtkWrappingTools-9.1.dylib                                                                                        (base) 
/Users/martin/Dev/jzy3d/public/vtk-java-natives/**vtkJavaNativesMacOSM1Impl**/src/main/resources/ch/unibas/cs/gravis/vtkjavanativelibs/impl/libvtkWrappingTools-9.1.9.1.0.dylib
```

```
martin@osxm1 ~/D/j/p/v/v/s/m/r/c/u/c/g/v/impl (main)> ls -ahl (realpath /private/var/folders/d2/85g_sxm91rg71yyky4gg6l6h0000gn/T/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib)
-rw-r--r--  1 martin  staff   395K  6 déc 10:38 /private/var/folders/d2/85g_sxm91rg71yyky4gg6l6h0000gn/T/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib
martin@osxm1 ~/D/j/p/v/v/s/m/r/c/u/c/g/v/impl (main)> ls -ahl (realpath /Users/martin/Dev/jzy3d/public/vtk-java-natives/vtkJavaNativesMacOSM1Impl/target/natives/m1/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib)
-rw-r--r--  1 martin  staff   418K  6 déc 11:15 /Users/martin/Dev/jzy3d/public/vtk-java-natives/vtkJavaNativesMacOSM1Impl/target/natives/m1/VtkNativeLibrariesImplMacOS_M1/vtkjavanatives-0.1/libvtkWrappingTools-9.1.dylib
```

**Comment by marcelluethi** [comment]
I finally got my hands on a Mac with an M1 processor and played around with the native libraries. I can confirm that this problem occurs. 

My tests were all done on my own fork, which is slightly older than your code and uses sbt instead of maven. But as I get exactly the behavior you describe here, I suppose my findings translate. 

It seems that the libraries are copied from the wrong jar, even though the right architecture is detected by the service loader. I got it to work by removing the dependency on `vtk-java-natives-macos`, such that only `vtk-java-natives-macosm1` is present. 

As a workaround, we can always ask the user to explicitly exclude the library that is not needed. But unfortunately I am currently totally clueless on how to fix this properly.

**Comment by jzy3d** [comment]
Thanks for sharing your insights. I'll dig again into this as soon as possible.
Another user of the (java/maven) library fixed this by making the M1 build with a specific suffix from CMAKE settings:

`BUILD_SUFFIX="arm64-${BUILD_VERSION}"`

> This gave the M1 dylibs their own unique name (before the x86 and M1 dylibs were named exactly the same, which caused problems when searching for them on the classpath). 
> I then was able to uniquely and correctly unpack and load the M1 dylibs at runtime from the M1 jars. 
> My initial testing shows everything is working as intended.

**Comment by marcelluethi** [comment]
Thanks for this information. I am still puzzled as to why having the same files in two different jars should lead to this problem. 
Anyway, if the classpath is the culprit, maybe a solution could involve using our own classloader?

**Comment by jzy3d** [comment]
I am not sure we should have to do this ourself!

Probably not related to our problem, but I am surprised that the [ServiceLoader used here](https://github.com/jzy3d/vtk-java-natives/blob/05127f582b0abe3fa1a59e40b0c0662c41246b60/vtkJavaNatives/src/main/java/ch/unibas/cs/gravis/vtkjavanativelibs/VtkNativeLibraries.java#L201) does not require resource files. 
I use a [ServiceLoader in another project](https://gitlab.com/jzy3d/panama-gl/-/blob/main/panama-gl-api/src/main/java/panamagl/factory/PanamaGLFactory.java#L139) which requires that all discovered service declare themselves through a [resource file in the META-INF folder as done here](https://gitlab.com/jzy3d/panama-gl/-/blob/main/panama-gl-wrappers-macos/src/main/resources/META-INF/services/panamagl.factory.PanamaGLFactory).

**Comment by marcelluethi** [comment]
I think this is what is achieved by the [autoservice](https://github.com/google/auto/tree/main/service) annotation. If you extract the jar file, you can find the generated file in the META-INF folder.

What still puzzles me is that the implementation of the service is loaded correctly  for M1, but the resources are taken from another jarfile. And according to your previous message, it can be mitigated by simply changing the file names. I would say that this is a bug if it were  not such an obviously wrong behavior, that somebody would have spotted this before.

**Comment by hococoder** [comment]
The way it looks to me is that when loading the M1 libs, you ask the class loader to load the given file name, so it looks on the class path - which has a particular order to it.  Apparently, the x86 mac jar comes *before* the M1 jar (all the jzy3d jars are in the path), so it encounters the x86 first, and therefore returns it.  It doesn't return all instances - just the first one it finds.  I tried a few ways to force it to load the M1 libs but couldn't find something that worked.
